# Generated by Django 2.0.13 on 2019-09-19 04:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('telecom', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('enrolled_date', models.DateTimeField(default=datetime.datetime(2019, 9, 19, 4, 35, 34, 391378, tzinfo=utc))),
            ],
        ),
    ]
