# Generated by Django 2.0.13 on 2019-09-19 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('telecom', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('enrolled_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Customar',
        ),
    ]
