# Generated by Django 2.0.13 on 2019-09-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='explaration_date',
            field=models.DateField(),
        ),
    ]
