# Generated by Django 2.0.13 on 2019-10-04 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0011_auto_20190927_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('support_type', models.CharField(choices=[('INSIDE', 'Inside'), ('OUTSIDE', 'Outside')], max_length=15)),
                ('customer_name', models.CharField(max_length=20)),
                ('requestment', models.TextField()),
                ('answer', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicalSupport', to='manager.Company')),
                ('support_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
